name: thakurji_jems
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  feature_discovery: ^0.14.1
  marquee: ^2.2.3
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.2
  intl: ^0.18.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.2.3
  dropdown_button2: ^2.3.9
  provider: ^6.0.5
  socket_io_client: ^2.0.3+1
  xml: ^6.2.2
  http: ^1.1.0
  shared_preferences: ^2.2.1
  fluttertoast: ^8.2.2
  firebase_messaging: ^14.2.1
  flutter_local_notifications: ^13.0.0
  firebase_core: ^2.25.4
  webview_flutter_android: ^3.1.3
  webview_flutter_wkwebview: ^3.2.2
  webview_flutter: ^4.0.1
  package_info_plus: ^4.2.0
  store_redirect: ^2.0.1
  share_plus: ^7.2.1
  notification_permissions: ^0.6.1
  curved_navigation_bar: ^1.0.3
#  in_app_review: ^2.0.8
  flutter_advanced_drawer: ^1.3.2
  app_settings: ^5.1.1
  open_settings_plus: ^0.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
